services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    working_dir: /var/www/project
    environment:
      - SERVER_HOST=0.0.0.0
      - HOME=/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8028:8000"
    volumes:
      - ./:/var/www

  vite:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_vite
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    working_dir: /var/www/project
    environment:
      - HOME=/tmp
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www

  pest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_pest
    user: "${UID:-1000}:${GID:-1000}"
    restart: unless-stopped
    working_dir: /var/www/project
    environment:
      - HOME=/tmp
      - APP_URL=http://app:8000
      - DB_CONNECTION=sqlite
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - app
    command: tail -f /dev/null
    volumes:
      - ./:/var/www
      - playwright_cache:/tmp/.cache/ms-playwright

volumes:
  playwright_cache: